name: ntv_flutter_wallet
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  solana: ^0.31.0

  http: ^1.1.0
  flutter_dotenv: ^5.2.1
  go_router: ^14.6.2
  bip39: ^1.0.6
  shared_preferences: ^2.3.3
  marquee: ^2.3.0
  shimmer: ^3.0.0
  fluttermoji: ^1.0.2
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  logger: ^2.5.0
  flutter_slidable: ^3.1.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/logo_medium.png
